###Sign up
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username":"tony1",
    "answer":"Tony"
}

###Get current user
GET http://localhost:3000/user/whoami

###Sign out
GET http://localhost:3000/user/signout

###Sign in
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "username":"tony12"
}

###Get current user prod
GET https://nestjs-production-f667.up.railway.app/user/whoami

###Sign up prod
POST https://nestjs-production-f667.up.railway.app/user/signup
Content-Type: application/json

{
    "username":"tony1",
    "answer":"Tony"
}

###Sign out prod
GET http://lnestjs-production-f667.up.railway.app/user/signout
